### ISSUE TITLE
Out-of-era Wonders and City-state quests

### ISSUE THREAD

**Issue by TheEXAM** [Sullien/Future-Expansion#4]
City-states currently give out quests to build wonders that are *technically* available to all players, but said wonders cannot be constructed due to the lack of actual technology for it. As you can see in the screenshots below, the city-state gave a quest to build a wonder that cannot be built at all yet since we are still in the Industrial Era.

![Screenshot_20220906-203624_UnCiv](https://user-images.githubusercontent.com/61744611/188639361-b6caf648-9e68-498a-8335-3727561d1d8e.jpg)
![Screenshot_20220906-203629_UnCiv](https://user-images.githubusercontent.com/61744611/188639365-820e9814-b8c8-44ab-9b84-cad174096186.jpg)
![Screenshot_20220906-203717_UnCiv](https://user-images.githubusercontent.com/61744611/188639367-f705a0b1-af5a-439a-a660-8dfe3b4ef73b.jpg)
![Screenshot_20220906-203708_UnCiv](https://user-images.githubusercontent.com/61744611/188639372-596771ce-7189-4cf9-89f1-5f2155dd783b.jpg)

A simple fix for this would be to assign a Tech/Era/Policy for each the wonders to become available.

**Comment by Sullien** [comment]
Thanks for the report. Will make sure this is fixed on the latest release.

**Comment by Sullien** [comment]
Closing as this bug is fixed.
