### ISSUE TITLE
Negative Culture Output

### ISSUE THREAD

**Issue by TheEXAM** [Sullien/Future-Expansion#5]
Something seems to be causing cities and wonders to have negative culture, which is normally impossible. I don't know what exactly is causing this, but I noticed it happen around when I adopted the Constitution policy. There could be some conflict in the codes for the Great Perks national wonders and Constitution policy, so I'm reporting this here for now.

Here are some screenshots of what I mean:
![Screenshot_20220910-003305_UnCiv](https://user-images.githubusercontent.com/61744611/189400010-eee485c7-405c-4138-b950-812964c5ffcd.jpg)
![Screenshot_20220910-003442_UnCiv](https://user-images.githubusercontent.com/61744611/189400036-72a252c2-2581-45c2-be78-e3f4bb5e780d.jpg)

I would love to also put the save game here for further troubleshooting, but I don't know how to post it without exceeding the text character limit.

**Comment by TheEXAM** [comment]
I seem to have found the underlying issue. The "-2 culture after adopting Constitution" of great perks is being applied to all cities even if the city is not where a great perk was built. So if you have 12 great perks and have adopted Constitution, the result is having -24 culture in each city, further multiplied by the respective culture multipliers within each city which then causes negative culture output.

![Screenshot_20220910-231739_UnCiv](https://user-images.githubusercontent.com/61744611/189489893-7b46a001-986c-4167-80f6-0259fa7b1b04.jpg)
![Screenshot_20220910-231843_UnCiv](https://user-images.githubusercontent.com/61744611/189489897-f5202f98-70b4-4464-a74e-ebf470bdfc55.jpg)

I think this can be fixed by changing the -2 culture application of the perks into "-2 culture in this city after adopting Constitution", so the -2 culture doesn't get applied to all cities.

**Comment by Sullien** [comment]
I see. That's a great solution. I'l apply it.

**Comment by Sullien** [comment]
This bug should be fixed now

**Comment by TheEXAM** [comment]
Yup all seems good.
![Screenshot_20220917-112720_Unciv](https://user-images.githubusercontent.com/61744611/190838852-03d74bc4-3cab-4002-8c5f-85bf34b23675.jpg)
